name = "St. Petersburg State Academy for Engineering Economics (ENGECON)
St. Petersburg State University of Engineering and Economics
St. Petersburg State Academy for Engineering Economics (ENGECON)
St. Petersburg State University of Engineering and Economics"
sld = "engec"
tld = "ru"
