name = "Moscow State Institute of Radiotechnics, Electronics and Automation (Technical University)
Moscow State Institute of Radiotechnics, Electronics and Automation (Technical University)"
sld = "mirea"
tld = "ru"
