name = "Yaroslavl International University of Business and New Technologies
Yaroslavl State Pedagogical University
Yaroslavl State Technical University
Yaroslavl International University of Business and New Technologies
Yaroslavl State Pedagogical University
Yaroslavl State Technical University"
sld = "yar"
tld = "ru"
