name = "Universidad Centroamericana de Ciencias Empresariales (UCEM)
Universidad Centroamericana de Ciencias Empresariales (UCEM)
Universidad Centroamericana de Ciencias Empresariales (UCEM)"
sld = "ucem"
tld = "edu.ni"
