name = "Universidad Internacional de Integración de América Latina
Universidad Internacional de Integración de América Latina
Universidad Internacional de Integración de América Latina"
sld = "unival"
tld = "edu.ni"
