name = "Universidad de las Regiones Autónomas de la Costa Caribe Nicaragüense
Universidad de las Regiones Autónomas de la Costa Caribe Nicaragüense
Universidad de las Regiones Autónomas de la Costa Caribe Nicaragüense"
sld = "uraccan"
tld = "edu.ni"
