name = "University of St. Michael's College
University of Toronto
University of Toronto, Mississauga
University of Toronto, Scarborough
University of Trinity College
Victoria University Toronto, University of Toronto"
sld = "utoronto"
tld = "ca"
