name = "St. Petersburg Repin State Academic Institute of Painting Sculpture and Achitecture
St. Petersburg Repin State Academic Institute of Painting Sculpture and Achitecture"
sld = "artacademy"
tld = "spb.ru"
