name = "American InterContinental University - London
American InterContinental University - Georgia
American InterContinental University - Ft. Lauderdale
American InterContinental University - Atlanta"
sld = "aiuniv"
tld = "edu"
