name = "Florida Metropolitan University, Fort Lauderdale College
Florida Metropolitan University, Tampa College
Florida Metropolitan University, Tampa College Brandon
Florida Metropolitan University, Tampa College Lakeland"
sld = "fmu"
tld = "edu"
