name = "Ecole Nationale Supérieure de Chimie de Clermont-Ferrand
Institut des Sciences de l'Ingénieur de Clermont-Ferrand
Université Blaise Pascal (Clermont-Ferrand II)"
sld = "univ-bpclermont"
tld = "fr"
