name = "University of Lower Silesia of the Association for the Advancement of Education in Wroclaw.
University of Lower Silesia of the Association for the Advancement of Education in Wroclaw."
sld = "dswe"
tld = "wroc.pl"
