name = "Leon Kozminski Academy of Entrepreneurship and Mangement
Leon Kozminski Academy of Entrepreneurship and Mangement in Warsaw
Leon Kozminski Academy of Entrepreneurship and Mangement
Leon Kozminski Academy of Entrepreneurship and Mangement in Warsaw"
sld = "wspiz"
tld = "edu.pl"
